test:
	./client/node_modules/karma/bin/karma start ./client/karma.conf.js --single-run

install-dependencies:
	npm install bootstrap --save-dev --prefix ./client
	npm install jquery --save-dev --prefix ./client
	npm install angular-mocks --save-dev --prefix ./client
	npm install karma --save-dev --prefix ./client
	npm install karma-jasmine --save-dev --prefix ./client
	npm install karma-chrome-launcher --save-dev --prefix ./client
